version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: bhumi-interior-mongodb-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: bhumi-interior-dev
    volumes:
      - mongodb_data_dev:/data/db
    networks:
      - bhumi-interior-dev-network

  # Backend API (Development with hot reload)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: bhumi-interior-backend-dev
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGO_URI: mongodb://admin:password123@mongodb:27017/bhumi-interior-dev?authSource=admin
      JWT_SECRET: dev-secret-key
      FRONTEND_URL: http://localhost:5173
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/uploads:/app/uploads
    depends_on:
      - mongodb
    networks:
      - bhumi-interior-dev-network
    command: npm run dev

volumes:
  mongodb_data_dev:

networks:
  bhumi-interior-dev-network:
    driver: bridge
